spring:
  profiles:
    active: dev
  jmx:
    enabled: false

rop:
#  platUrl: http://127.0.0.1:8084/router
#  zfUrl: http://127.0.0.1:8084/router
  platUrl: http://10.45.47.90:7003/router
  zfUrl: http://10.45.47.90:7003/router

server:
  port: 8081

logging.level.com.iwhalecloud.retail.oms.mapper: debug

mybatis-plus:
  mapperLocations: classpath:oms/mapper/*.xml
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.47.88:3306/retail
    username: retail
    password: retail123
  
jwt:
  secret: A5-!^!.X3K
  expiresAt: 720   #token生效时间（分钟）
  
wechat:
   mp:
      appId: wx784aec4d305f090b
      secret: 2b2c41af036507b5251c94cd3bef61c3
      token: iwhalecloud
      aesKey: 62pJy1IiQvjMgNeEpCp4ZMV2DA5qrfrm85YP8B5c3P9


# 分布式文件系统FDFS配置
fdfs:
  showUrl: http://10.45.47.87:8081/
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
      width: 150
      height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port :NRetail/NRetail
    - 10.45.47.87:22133
    - 10.45.47.90:22133
    - 10.45.47.87:22133
  pool:
    jmx-enabled: false